/**
 * hook-run.ts
 * Invoked by Claude Code hooks (via settings.json).
 * Reads the hook event JSON from stdin, then acts on it.
 *
 * Claude Code sends this JSON on stdin for every hook call:
 * {
 *   "session_id": "...",
 *   "transcript_path": "/path/to/transcript.jsonl",
 *   "cwd": "/current/working/dir",
 *   "hook_event_name": "SessionStart" | "Stop" | "SessionEnd" | ...,
 *   "stop_hook_active": true | false,   // Stop only — prevents loops
 *   "tool_name": "...",                 // PreToolUse / PostToolUse only
 *   "tool_input": {...}                 // PreToolUse / PostToolUse only
 * }
 *
 * Supported events:
 *   SessionStart — log session_start event, optionally regenerate CLAUDE.md
 *   Stop / SessionEnd — log session_end, sync Obsidian, regenerate CLAUDE.md
 */

import * as path from 'path';
import * as fs from 'fs';
import { findProject } from '../lib/project.js';
import { appendEvent } from '../lib/events.js';
import { touchProject } from '../lib/registry.js';
import { generateClaudeMd, isAutoGenerated } from './generate-claude-md.js';
import { resolvePaths } from '../lib/paths.js';

// ── Types ─────────────────────────────────────────────────────────────────────

interface HookPayload {
  session_id?: string;
  transcript_path?: string;
  cwd?: string;
  hook_event_name?: string;
  stop_hook_active?: boolean;
  tool_name?: string;
  tool_input?: Record<string, unknown>;
  [key: string]: unknown;
}

// ── stdin reader ──────────────────────────────────────────────────────────────

async function readStdin(): Promise<string> {
  return new Promise((resolve) => {
    let buf = '';
    const timeout = setTimeout(() => resolve(buf), 1000); // don't hang if no stdin
    process.stdin.setEncoding('utf-8');
    process.stdin.on('data', (chunk) => { buf += chunk; });
    process.stdin.on('end', () => { clearTimeout(timeout); resolve(buf); });
    // If stdin is a TTY (direct terminal invocation), resolve immediately
    if (process.stdin.isTTY) { clearTimeout(timeout); resolve(''); }
  });
}

// ── Obsidian sync (optional, silent on failure) ───────────────────────────────

function runSync(project: ReturnType<typeof findProject>): void {
  if (!project) return;
  const paths = resolvePaths(project.project, project.projectDir);
  if (!fs.existsSync(paths.obsidianVault)) return;
  if (!fs.existsSync(paths.memoryDir)) return;

  try {
    fs.mkdirSync(paths.obsidianProjectDir, { recursive: true });
    const files = fs.readdirSync(paths.memoryDir).filter((f) => f.endsWith('.md'));
    for (const filename of files) {
      const src  = path.join(paths.memoryDir, filename);
      const dest = path.join(paths.obsidianProjectDir, filename);
      fs.writeFileSync(dest, fs.readFileSync(src, 'utf-8'), 'utf-8');
    }
  } catch {
    // Sync failures must never crash the hook — Claude Code would show an error
  }
}

// ── CLAUDE.md regeneration (only if it's our generated file) ─────────────────

function refreshClaudeMd(found: ReturnType<typeof findProject>): void {
  if (!found) return;
  const claudeMdPath = path.join(found.projectDir, 'CLAUDE.md');
  // Only regenerate if: file doesn't exist yet, OR it's already ours
  if (fs.existsSync(claudeMdPath) && !isAutoGenerated(claudeMdPath)) return;
  try {
    generateClaudeMd({ quiet: true });
  } catch {
    // Never crash the hook
  }
}

// ── Event handlers ────────────────────────────────────────────────────────────

function handleSessionStart(payload: HookPayload): void {
  // Change to the session's cwd so findProject walks up from the right place
  const cwd = payload.cwd;
  if (cwd && fs.existsSync(cwd)) {
    try { process.chdir(cwd); } catch { /* ignore */ }
  }

  const found = findProject();
  if (!found) return; // not a claude-project directory — silent exit

  const { project } = found;

  appendEvent(project, 'session_start', {
    summary: `Session started (${payload.session_id?.slice(0, 8) ?? 'unknown'})`,
    session_id: payload.session_id ?? '',
    cwd: payload.cwd ?? process.cwd(),
  });

  touchProject(project.project_id);

  // Refresh CLAUDE.md so it's up-to-date for this session
  refreshClaudeMd(found);
}

function handleStop(payload: HookPayload): void {
  // Guard: stop_hook_active prevents infinite loops
  if (payload.stop_hook_active) return;

  const cwd = payload.cwd;
  if (cwd && fs.existsSync(cwd)) {
    try { process.chdir(cwd); } catch { /* ignore */ }
  }

  const found = findProject();
  if (!found) return;

  const { project } = found;

  appendEvent(project, 'session_end', {
    summary: `Session ended (${payload.session_id?.slice(0, 8) ?? 'unknown'})`,
    session_id: payload.session_id ?? '',
    cwd: payload.cwd ?? process.cwd(),
  });

  touchProject(project.project_id);

  // Sync memory → Obsidian
  runSync(found);

  // Refresh CLAUDE.md so next session starts fresh
  refreshClaudeMd(found);
}

// ── Entry point ───────────────────────────────────────────────────────────────

export async function hookRun(event: string): Promise<void> {
  const raw = await readStdin();

  let payload: HookPayload = {};
  if (raw.trim()) {
    try {
      payload = JSON.parse(raw) as HookPayload;
    } catch {
      // stdin wasn't JSON — use empty payload, still proceed
    }
  }

  // Normalise event name: accept CLI arg or hook_event_name from payload
  const eventName = (event || payload.hook_event_name || '').toLowerCase();

  switch (eventName) {
    case 'sessionstart':
    case 'session_start':
      handleSessionStart(payload);
      break;

    case 'stop':
    case 'sessionend':
    case 'session_end':
      handleStop(payload);
      break;

    default:
      // Unknown event — log it generically if we're in a project
      if (payload.cwd && fs.existsSync(payload.cwd)) {
        try { process.chdir(payload.cwd); } catch { /* ignore */ }
      }
      const found = findProject();
      if (found) {
        appendEvent(found.project, `hook_${eventName}`, {
          session_id: payload.session_id ?? '',
          raw_event: payload.hook_event_name ?? event,
        });
      }
      break;
  }
}
