# Fortify AST Scan — Enterprise security scanning
# REQUIRES: Fortify license + FOD_TENANT, FOD_USER, FOD_PAT secrets
# To enable: set FORTIFY_ENABLED repository variable to 'true'
# Docs: https://github.com/fortify/github-action

name: Fortify AST Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '20 14 * * 6'  # Weekly Saturday scan

jobs:
  Fortify-AST-Scan:
    runs-on: ubuntu-latest
    if: ${{ vars.FORTIFY_ENABLED == 'true' }}
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v6

      - name: Run Fortify AST Scan
        uses: fortify/github-action@v1
        with:
          sast-scan: true
        env:
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{ secrets.FOD_TENANT }}
          FOD_USER: ${{ secrets.FOD_USER }}
          FOD_PASSWORD: ${{ secrets.FOD_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
